components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/java/org/wso2/carbon/user/mgt/ui/UserAdminUIConstants.java, components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp, components/user-manager/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/UserRealmProxy.java
fix to jira : https://wso2.org/jira/browse/IDENTITY-3025
=> Identity-3025

components/event/org.wso2.carbon.event.admin/src/main/java/org/wso2/carbon/event/admin/internal/TopicManagerAdminService.java, components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/EventBroker.java, components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/CarbonEventBroker.java, components/event/org.wso2.carbon.event.ws/src/main/java/org/wso2/carbon/event/ws/internal/receivers/CarbonEventingMessageReceiver.java
Modified method name for spelling correction.
=> Event component - Refactoring.

components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/bulk-import.jsp
Fix for IDENTITY-3105 ( https://wso2.org/jira/browse/IDENTITY-3105 )
=> Bulk import validation for non-empty password field

components/userstore-config/org.wso2.carbon.identity.user.store.configuration.ui/src/main/java/org/wso2/carbon/identity/user/store/configuration/ui/utils/UserStoreUIUtils.java
https://wso2.org/jira/browse/IDENTITY-2646
=> Fix for IDENTITY-2646

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/AbstractTask.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/TaskQuartzJobAdapter.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/remote/RemoteTaskManager.java, components/ntask/org.wso2.carbon.ntask.solutions/src/main/java/org/wso2/carbon/ntask/solutions/webservice/WebServiceCallTask.java
Reverts wso2/carbon-commons#116
=> Revert "Fixing JIRA CARBON-15351"

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/dscommon.js
https://wso2.org/jira/browse/CARBON-15358
=> Fixing CARBON-15358

components/event/org.wso2.carbon.event.ui/src/main/resources/META-INF/component.xml
JIRA - https://wso2.org/jira/browse/MB-889
=> [MB-889] Added permissions for topic in UI.

components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subtopic.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/topic_add.jsp
Event component - resource bundle reference fix.
=> Event component - resource bundle reference fix.

components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
JIRA - https://wso2.org/jira/browse/MB-1201
There was an issue of using a String array for getting the user roles and removing admin and anonymous users.
Therefore now using an Array list and iterator to remove those roles.
=> [MB-1201] Modified method in getting user roles when adding a topic in event component through UI

components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java, components/event/org.wso2.carbon.event.ui/src/main/resources/META-INF/component.xml
Modification to getUserRole method in Event Component. Added permissions for topics menu.
=> Modification to getUserRole method in Event Component. Added permissions for topics menu.

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/LoggingAdmin.java
Haven't remove debug log message, since it will help user to identify appender name.
=> Fix for WSAS-2120

components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/builder/EventBrokerBuilderDS.java
=> removing andes specific package name checks

components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/resources/xslt/tryit.xslt
https://wso2.org/jira/browse/CCOMMONS-16
=> CCOMMONS-16:Adding content-type text/javascript to edit_area_full.js resource url

components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subscription_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_topic_to_backend_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/delete_topic_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/renewSubscriptions.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/renew_subscription_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/topics.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/try_it_out_invoke_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/unsubscribe_from_topic_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/update_role_permissions_ajaxprocessor.jsp, components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/update_role_permissions_from_session_ajaxprocessor.jsp
=> CCOMMONS-15 : Changing state changing operation from GET to POST and blocking POST in EventUi

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/deletedatasource-ajaxprocessor.jsp, components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/dialog.jsp, components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/dscommon.js, components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/newdatasource.jsp, components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/savedatasource-ajaxprocessor.jsp
https://wso2.org/jira/browse/CCOMMONS-18
=> Changing state changing GET requests to POST

components/wsdl-tools/wsdl2code/org.wso2.carbon.modules.wsdl2code.ui/pom.xml, components/wsdl-tools/wsdl2code/org.wso2.carbon.modules.wsdl2code.ui/src/main/resources/web/wsdl2code/index.jsp, pom.xml
Apply proper encoding where appropriate
=> Apply proper output encoding

components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator.ui/src/main/resources/web/wsdl_validator/index.jsp, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/pom.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/main/java/org/wso2/carbon/tools/wsdlvalidator/WsdlValidator.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/main/java/org/wso2/carbon/tools/wsdlvalidator/exception/WSDLValidatorException.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/java/org/wso2/carbon/tools/wsdlvalidator/test/WSDLValidatorXXETest.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/java/org/wso2/carbon/tools/wsdlvalidator/test/constants/XXEResourceConstants.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/java/org/wso2/carbon/tools/wsdlvalidator/test/models/XXEResource.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/testng.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/filenotfound.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/ftp.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/insidesoapbody.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/onbextraction1.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/onbextraction2.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/onbextraerror.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/onbextranice.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/onbvariation.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/outboundxxe.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/validwsdl.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/resources/xxe/wafbypass.xml
Identitifed issues when validating WSDL XML input stream fixed
=> Fix WSDL parser validation issues

components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/main/java/org/wso2/carbon/tools/wsdlvalidator/WsdlValidator.java, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/test/java/org/wso2/carbon/tools/wsdlvalidator/test/WSDLValidatorXXETest.java
Possible TransformerFactory.newInstance(String, ClassLoader) method not found on certain versions fixed
=> Fix possible method not found error

components/wsdl2form/org.wso2.carbon.wsdl2form/pom.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/java/org/wso2/carbon/wsdl2form/Util.java, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/java/org/wso2/carbon/wsdl2form/test/WSDLFormValidatorXXETest.java, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/java/org/wso2/carbon/wsdl2form/test/constants/XXEResourceConstants.java, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/java/org/wso2/carbon/wsdl2form/test/models/XXEResource.java, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/testng.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/filenotfound.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/ftp.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/insidesoapbody.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/onbextraction1.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/onbextraction2.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/onbextraerror.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/onbextranice.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/onbvariation.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/outboundxxe.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/validwsdl.xml, components/wsdl2form/org.wso2.carbon.wsdl2form/src/test/resources/xxe/wafbypass.xml
Identitifed issues when validating WSDL XML input stream fixed
=> Fix WSDL tryit validation issues

components/caching-invalidator/org.wso2.carbon.caching.invalidator/src/main/java/org/wso2/carbon/caching/invalidator/amqp/ConfigurationManager.java, components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/builder/EventBrokerBuilder.java
This fix is added to get the configuration folder, using kernel configurations. without hardcoding the path
=> Fix configuration paths

components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/java/org/wso2/carbon/wsdl2form/WSDL2FormGenerator.java
Fix for https://github.com/wso2/product-ei/issues/234
=> Commenting out redirection code as it fails tryit tool in EI

components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/java/org/wso2/carbon/wsdl2form/WSDL2FormGenerator.java
Reverts wso2/carbon-commons#259
=> Revert "Commenting out redirection code as it fails tryit tool in EI"

components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/update_logger-ajaxprocessor.jsp
https://github.com/wso2/product-ei/issues/496
=> Fix UI issue in Logging Configuration page

components/caching-invalidator/org.wso2.carbon.caching.invalidator/src/main/java/org/wso2/carbon/caching/invalidator/amqp/ConfigurationManager.java, components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/builder/EventBrokerBuilder.java
Porting fix : https://github.com/wso2/carbon-commons/pull/257 to master branch
Fix for getting the configuration folder, using kernel configurations. without hardcoding the path
=> Fix configuration path

README.md
This pull request updates title in root README.md file from "carbon-commons" to "Carbon Commons". Thanks!
=> Updating title in root README.md file

pom.xml
=> updating httpclient version

pom.xml
> Resolves issue: https://github.com/wso2/carbon-commons/issues/288
> Updates the httpclient version to 4.3.6.wso2v1
=> Update httpclient dependency version

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/util/LoggingUtil.java
BufferedReader and InputStreamReader are not closed properly in a finally block. Instead of that this will use java7 try with resource style
=> Use java7 try with resource

components/soap-tracer/org.wso2.carbon.tracer/src/main/java/org/wso2/carbon/tracer/service/TracerAdmin.java
> Resolves https://github.com/wso2/carbon-commons/issues/289
> Remove request parameter from error message
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” …
=> Remove request parameter from error message

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskUtils.java
> Improve xml parsing logic
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Improve xml parsing logic

components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/resources/xslt/tryit.xslt
Add text/javascript content type for edit-area js
Issue - https://github.com/wso2/product-ei/issues/1745
> Link to the PR for …
=> Add text/javascript content type for edit-area js

components/application-mgt/org.wso2.carbon.application.mgt.ui/src/main/resources/web/carbonapps/app_upload.jsp
A CSRF error is produced when uploading a CApp through the management console. This PR fixes it.
Issue - https://github.com/wso2/product-ei/issues/1787
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Fix csrf error when uploading capp from mgt console

components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/java/org/wso2/carbon/wsdl2form/WSDL2FormGenerator.java, components/wsdl2form/org.wso2.carbon.wsdl2form/src/main/resources/xslt/tryit.xslt
> To resolve CSRF attack thwarted error in tryit tool of EI
> Resolves wso2/product-ei#1900
> Cherry-picked the fix from [1].
[1] https://github.com/wso2/carbon-commons/pull/235
=> Fix CSRF attack thwarted error - tryit tool in EI

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java
Fix XXE vulnerability of DocumentBuilderFactory at NDataSourceHelper.
> Link(s) to product documentation that addresses the …
=> Fix XXE vulnerability in NDataSourceHelper

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskUtils.java
Fix XXE vulnerability with DocumentBuilder at TaskUtils.
> Link(s) to product documentation that addresses the changes of this …
=> Fix XXE vulnerability at TaskUtils

pom.xml
Change libthrift version to 0.7.0.wso2v2.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Change libthrift version

components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/appenders-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/globalLogConfig-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/log-admin.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/loggers-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/restoreDefaults-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/syslogConfig-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/updateLog4jGlobal-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/update_appender_ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/update_logger-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/update_syslog-ajaxprocessor.jsp
License header is appended to pop up window of configure->Logging UI
This PR is to fix it.
Related issue is https://github.com/wso2/product-ei/issues/2054
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …
=> Fix showing license header in the logging UI

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskServiceContext.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RuleBasedLocationResolver.java
Fix wso2/product-ei#2111
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add localMemberIdentifier for RuleBasedLocationResolver

components/tenant-mgt-common/org.wso2.carbon.tenant.common/pom.xml, pom.xml
Generate unit test coverage information
Integrate Jacoco Maven plugin with Maven Surefire plugin to generate unit test coverage information
=> Jacoco plugin integration

components/logging/org.wso2.carbon.logging.service/pom.xml, components/transaction-manager/org.wso2.carbon.transaction.manager/src/main/java/org/wso2/carbon/transaction/manager/TransactionManagerComponent.java, features/event/org.wso2.carbon.event.common.feature/pom.xml, features/event/org.wso2.carbon.event.server.feature/pom.xml, features/system-statistics/org.wso2.carbon.system.statistics.server.feature/pom.xml, features/tenant-mgt-common/org.wso2.carbon.tenant.mgt.common.server.feature/pom.xml, features/wsdl-tools/org.wso2.carbon.wsdl.tools.server.feature/pom.xml
Remove unwanted kernel feature dependencies
=> Remove unnecessary dependencies

components/transaction-manager/org.wso2.carbon.transaction.manager/src/main/java/org/wso2/carbon/transaction/manager/TransactionManagerComponent.java
=> Fix Transaction Manager

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/FileBasedTaskRepository.java
=> Fix FileNotFoundError in FilebasedTaskRepository

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/FileBasedTaskRepository.java
=> code cleanup

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/FileBasedTaskRepository.java
> Fix synapse configs deployment issue in lightESB.
> Remove URI
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to …
=> Fix synapse configs deployment issue in lightESB.

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/FileBasedTaskRepository.java
> Fix cleaning meta files during task deletion
=> Fix cleaning meta files during task deletion

components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subtopic.jsp
Add necessary encodings
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
=> Fix XSS vulnerability

pom.xml
Update axis2 transport version for the weekly release.
=> Update axis2 transport version

pom.xml
Update axis2transport version for the weekly release
=> Update axis2transport version

components/application-mgt/org.wso2.carbon.application.mgt/src/main/java/org/wso2/carbon/application/mgt/ApplicationAdmin.java
> Introduced DS_TYPE constant in ApplicationAdmin class.
=> Introduce DS_TYPE constant in ApplicationAdmin class

components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/pom.xml, pom.xml
> To add javax.activation.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add javax.activation import to tools.wsdlvalidator

components/logging/pom.xml, components/transaction-manager/org.wso2.carbon.transaction.manager/pom.xml, components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/pom.xml, components/wsdl-tools/wsdlvalidator/pom.xml, pom.xml
> To update jboss-transaction, slf4j and jacoco version
> Link to the PR for changes to the training content in …
=> Version update

components/event/org.wso2.carbon.event.admin/pom.xml, components/tryit/org.wso2.carbon.tryit.ui/pom.xml, pom.xml
> To change the commons.httpclient dependency.
> Link to the PR for changes to the training content in …
=> Modifying httpcommons dependency

pom.xml
related Issue :- https://github.com/wso2/product-ei/issues/2061
Removes duplicate jar
=> Upgrade jackson-databind version.

pom.xml
https://github.com/wso2/product-is/issues/4652
=> Update libthrift version t0 0.12.0

components/logging/org.wso2.carbon.logging.summarizer/pom.xml, features/logging-mgt/org.wso2.carbon.logging.summarizer.server.feature/pom.xml, pom.xml
https://github.com/wso2/product-is/issues/4652
=> Update libthrift version to 0.12.0

components/hostobjects/org.wso2.carbon.hostobjects.sso/pom.xml, pom.xml
=> Upgrade axis2 |  axis2 transport | kernel | GSON | Codec Versions

pom.xml
This PR is to update the Jackson dependency version.
=>  Bump dependency versions

components/logging/org.wso2.carbon.logging.service/pom.xml, components/logging/org.wso2.carbon.logging.summarizer/pom.xml, features/logging-mgt/org.wso2.carbon.logging.summarizer.server.feature/pom.xml, pom.xml
https://github.com/wso2/product-is/issues/4652
=> Upgrade guava version in carbon-commons

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java, components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/validateconnection-ajaxprocessor.jsp, pom.xml
Encode request parameters in the NDataSourceHelper and validateconnection-ajaxprocessor.jsp
> Link(s) to product documentation …
=> Encode request parameters in validate connection

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/newdatasource.jsp
Fix the issue of logging datasource password in http_access_management_console logs, while testing the connection via management console.
> Brief description of the new feature or bug fix as it will appear in the …
=> Fix the issue of logging datasource password

components/logging/org.wso2.carbon.logging.summarizer/pom.xml, features/logging-mgt/org.wso2.carbon.logging.summarizer.server.feature/pom.xml, pom.xml
=> Upgrade versions

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/newdatasource.jsp
=> carbon-ndatasource-ui: update newdatasource.jsp

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java
Improve XML transformer logic for import javax.xml.transform.Transformer.
=> Improve xml transformer logic

components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/delivery/jms/QpidJMSDeliveryManagerFactory.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskUtils.java, pom.xml
- Change the `org.wso2.securevault` version to 1.1.2
- Resolve the secrets using `MiscellaneousUtil.resolve()` method.
=> Add secure-vault changes.

pom.xml
Update axiom dependency version to fix the build break
=> Update axiom dependency version

pom.xml
Fix build failure due to missing java doc plugging
=> Fix build failure due to java doc

pom.xml
>Remove url-mapper component 
>Remove tomcat dependency
=> Remove url-mapper component  and tomcat dependency

features/application-mgt/org.wso2.carbon.application.mgt.feature/pom.xml, features/deployment-synchronizer/org.wso2.carbon.deployment.synchronizer.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.ui.feature/pom.xml, features/ws-discovery/org.wso2.carbon.discovery.ui.feature/pom.xml
>Add kernel feature import version
=> Add kernel feature import version

features/reporting/org.wso2.carbon.reporting.ui.feature/pom.xml
> Fix import version for the org.wso2.carbon.ui.menu.tools
=> Fix import version for the org.wso2.carbon.ui.menu.tools

pom.xml
=> Update Axis2-Transport version

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/newdatasource.jsp
Fixes https://github.com/wso2/product-ei/issues/4667
=> Fix https://github.com/wso2/product-ei/issues/4667

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusterGroupCommunicator.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/service/TaskService.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/service/impl/TaskServiceImpl.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/service/impl/TaskServiceXMLConfiguration.java, features/ntask/org.wso2.carbon.ntask.core.feature/resources/conf/tasks-config.xml, features/ntask/org.wso2.carbon.ntask.core.feature/src/main/resources/conf/tasks-config.xml
> This PR will fix the issue of the tasks not getting scheduled when Location based Resolving Fails. Basically, when a suitable task node joins the cluster, the task scheduling should happen and evaluate the rules.
Fixes : wso2/product-ei#4335
=> Fix tasks are not getting scheduled when Location based Resolving Fails

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/AbstractQuartzTaskManager.java
Fixes https://github.com/wso2/product-ei/issues/4748
When a scheduled task has a cron expression which will never get triggered in future, quartz throws an exception. Since EI is not handling the exception properly, Task Manager might not get initialised when starting the server. The issue can occur in both Standalone and Clustered environments. This PR changes the Quartz Manager so that it will not try to schedule the job that will never get triggered.
=> Handle scheduled tasks whose trigger will never get fired

pom.xml
Upgrade kernel feature version
> Upgrade kernel feature version
=> Upgrade kernel feature version

pom.xml
>Parameterize the feature version
=> Parameterize the feature version

features/tenant-mgt-common/org.wso2.carbon.tenant.mgt.common.server.feature/pom.xml
=> Change compatible carbon.core.server feature version range

components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java
this is an improvement for the https://github.com/wso2/carbon-commons/pull/349
return is used to pretifyxml.see [1].
[1] https://github.com/nalakas/carbon-commons-1/blob/a2866804234525e60278878ad1fd693af1fa762f/components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/java/org/wso2/carbon/ndatasource/ui/NDataSourceHelper.java#L577
=> return empty string if empty element

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/FileBasedTaskRepository.java
> Fix improper restriction of XXE
=> Fix improper restriction of XXE

components/uuid-generator/org.wso2.carbon.uuid.generator/pom.xml, features/tenant-mgt-common/org.wso2.carbon.tenant.mgt.common.feature/pom.xml, features/tenant-mgt-common/org.wso2.carbon.tenant.mgt.common.server.feature/pom.xml, features/tenant-mgt-common/org.wso2.carbon.tenant.mgt.common.ui.feature/pom.xml, features/uuid-generator/org.wso2.carbon.uuid.generator.feature/pom.xml, features/uuid-generator/org.wso2.carbon.uuid.generator.server.feature/pom.xml
=> Add parent relative path

components/wsdl-tools/wsdlvalidator/org.wso2.carbon.tools.wsdlvalidator/src/main/java/org/wso2/carbon/tools/wsdlvalidator/WsdlValidator.java
=> Implement secure XML parsing

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
related to https://github.com/wso2/product-is/issues/8047
Merging order should be 
https://github.com/wso2/carbon-commons/pull/413
https://github.com/wso2/carbon-multitenancy/pull/190
https://github.com/wso2/identity-api-server/pull/150
https://github.com/wso2/identity-rest-dispatcher/pull/165
> Brief description of the new feature or bug fix as it will appear in the …
=> Add a new error code for invalid tenant id case

components/logging/org.wso2.carbon.logging.view.ui/pom.xml, features/logging-mgt/org.wso2.carbon.logging.mgt.ui.feature/pom.xml
>Change feature pom versions to match the latest release.
=> Change feature pom version to match the release.

components/tryit/org.wso2.carbon.tryit/src/main/java/org/wso2/carbon/tryit/TryitRequestProcessor.java
PR https://github.com/wso2/carbon-commons/pull/340
=> Improve PR_340

components/tryit/org.wso2.carbon.tryit.ui/src/main/resources/org/wso2/carbon/tryit/ui/i18n/Resources.properties, components/tryit/org.wso2.carbon.tryit.ui/src/main/resources/web/tryit/index.jsp
=> Disable tryit if disabled via system property

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
> Introduce new error code TM-60015 for tenant domain not found case.
=> Introduce tenant domain not found error code.

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
Related to https://github.com/wso2/product-is/issues/9462
=> Add new error code

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
Public fix : https://github.com/wso2/product-ei/issues/5221
=> Skip deletion of tasks scheduled in other nodes

.gitignore, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/util/CommonUtil.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/util/StratosConfiguration.java
Add regex pattern config for the tenant domain name
As a part of https://github.com/wso2/product-is/issues/11485
=> Add regex pattern config for tenant domain name

components/logging/org.wso2.carbon.logging.admin.ui/pom.xml, components/logging/org.wso2.carbon.logging.service/pom.xml, features/logging-mgt/org.wso2.carbon.logging.mgt.feature/pom.xml, service-stubs/logging/org.wso2.carbon.logging.admin.stub/pom.xml
Change versions in logging-mgt module
=> Change versions in logging-mgt module

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/exception/StratosClientException.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/exception/TenantManagementClientException.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/exception/TenantManagementServerException.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/exception/TenantMgtException.java, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/listeners/TenantMgtListener.java
Related to https://github.com/wso2/product-is/issues/11967
=> Add pre tenant add listener

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
=> Add tenant creation error message

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/listeners/TenantMgtListener.java
> Add onPostdelete public method to tenantMgtListener interface
=> Add onPostDelete to tenantMgtListener

components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/LogConfigUpdater.java
=> fix pax-logging latest version support

components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/GoogleAnalyticsDataPublisher.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/test/java/org/wso2/carbon/ganalytics/publisher/GoogleAnalyticsDataPublisherTest.java, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/LogConfigUpdater.java
=> Add update fixes to  4.7.x

components/logging/org.wso2.carbon.logging.updater/pom.xml, pom.xml
=> [4.7.x] Upgrade pax-logging to 2.1.0

components/system-statistics/org.wso2.carbon.statistics/pom.xml
=> remove log4j1 reference

pom.xml
=> [4.7.x] Update kernel version

features/ntask/org.wso2.carbon.ntask.core.feature/pom.xml
=> remove slf4j api

components/system-statistics/org.wso2.carbon.statistics/pom.xml, components/wsdl-tools/wsdl2code/org.wso2.carbon.modules.wsdl2code/src/main/java/org/wso2/carbon/wsdl2code/codegen-pom.xsl, pom.xml
$subject
backport : https://github.com/wso2-support/carbon-commons/pull/290
=> upgrade log4j dependencies

components/logging/org.wso2.carbon.logging.view/pom.xml, pom.xml
=> Switch for WSO2 managed pax logging

components/logging/org.wso2.carbon.logging.updater/pom.xml, components/system-statistics/org.wso2.carbon.statistics/pom.xml, pom.xml
=> Rollback to log4j1

components/message-flows/org.wso2.carbon.messageflows.ui/pom.xml, components/message-flows/org.wso2.carbon.messageflows/pom.xml, features/application-mgt/org.wso2.carbon.application.mgt.feature/pom.xml, features/application-mgt/org.wso2.carbon.application.mgt.server.feature/pom.xml, features/deployment-synchronizer/org.wso2.carbon.deployment.synchronizer.feature/pom.xml, features/deployment-synchronizer/org.wso2.carbon.deployment.synchronizer.git.feature/pom.xml, features/deployment-synchronizer/org.wso2.carbon.deployment.synchronizer.server.feature/pom.xml, features/event/org.wso2.carbon.event.feature/pom.xml, features/event/org.wso2.carbon.event.server.feature/pom.xml, features/event/org.wso2.carbon.event.ui.feature/pom.xml, features/logging-mgt/org.wso2.carbon.logging.mgt.feature/pom.xml, features/logging-mgt/org.wso2.carbon.logging.mgt.ui.feature/pom.xml, features/ndatasource/org.wso2.carbon.ndatasource.feature/pom.xml, features/ntask/org.wso2.carbon.ntask.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.server.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.template.server.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.template.ui.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.ui.feature/pom.xml, features/system-statistics/org.wso2.carbon.system.statistics.feature/pom.xml, features/system-statistics/org.wso2.carbon.system.statistics.server.feature/pom.xml, features/transaction-manager/org.wso2.carbon.transaction.manager.feature/pom.xml, features/tryit/org.wso2.carbon.tryit.feature/pom.xml, pom.xml
Update carbon.commons.version property to refer to the project version.
=> Update carbon.commons.version property to refer to the project version.

components/ntask/org.wso2.carbon.ntask.core/pom.xml, features/ntask/org.wso2.carbon.ntask.core.feature/pom.xml, pom.xml
* Updating the third party dependencies.
* Orbit bundle - https://github.com/wso2/orbit/blob/master/quartz/2.3.2.wso2v1/pom.xml
=> Update dependencies in carbon-commons

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
fixes https://github.com/wso2/api-manager/issues/512
=> Remove Hazelcast Lock Since APIM not using HZ anymore

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskServiceContext.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RoundRobinTaskLocationResolver.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RuleBasedLocationResolver.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusterGroupCommunicator.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
This PR addresses the changes required in PR https://github.com/wso2/carbon-commons/pull/463.
But since the above PR is already merged, changes will be addressed in this PR.
=> [4.9.x] Addressed the required changes

components/ganalytics/org.wso2.carbon.ganalytics.publisher/pom.xml, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/GoogleAnalytics4Constants.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/GoogleAnalytics4Data.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/GoogleAnalytics4DataPublisher.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/event/CustomEvent.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/event/Event.java, components/ganalytics/org.wso2.carbon.ganalytics.publisher/src/main/java/org/wso2/carbon/ganalytics/publisher/ga4/event/PageViewEvent.java, components/ganalytics/pom.xml
Fix https://github.com/wso2/api-manager/issues/1393
=> Add implementation for Google Analytics 4 publishing

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
Fixes https://github.com/wso2/api-manager/issues/1771
=> Fix api-manager/issues/1771

components/logging/org.wso2.carbon.logging.remote.config.ui/pom.xml, features/logging-mgt/org.wso2.carbon.logging.remote.config.mgt.feature/pom.xml, features/logging-mgt/org.wso2.carbon.logging.remote.config.mgt.ui.feature/pom.xml, service-stubs/logging/org.wso2.carbon.logging.remote.config.stub/pom.xml
=> Update pom version of new component

components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/java/org/wso2/carbon/logging/remote/config/ui/RemoteLoggingConfigClient.java, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/org/wso2/carbon/logging/remote/config/ui/i18n/Resources.properties, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/add_remote_server_config-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/js/loggingconfig.js, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/process_add_remote_server_config-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.service/pom.xml, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/LoggingConstants.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfigService.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/data/RemoteServerLoggerData.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigDataHolder.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigServiceComponent.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/util/Utils.java, components/logging/org.wso2.carbon.logging.updater/pom.xml, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/RemoteLoggingConfigUpdater.java, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/internal/DataHolder.java, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/internal/LoggingUpdaterServiceComponent.java, service-stubs/logging/org.wso2.carbon.logging.remote.config.stub/src/main/resources/RemoteLogConfig.wsdl
- Improve Remote server logger data service to return config data
- store remote server logger config data in the registry
- https://github.com/wso2/product-is/issues/16697
- https://github.com/wso2/api-manager/issues/1565
=> Improve service component to get remote server logger config data

components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskServiceContext.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RoundRobinTaskLocationResolver.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RuleBasedLocationResolver.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusterGroupCommunicator.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java, components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/internal/TasksDSComponent.java
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> [4.10.x] Hazelcast Removal 

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/LoggingConstants.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java
> Fix issue when resetting remote log publishing settings for audit logs
- https://github.com/wso2/carbon-commons/pull/484
=> Fix remote login audit log reset issue

components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/java/org/wso2/carbon/logging/remote/config/ui/RemoteLoggingConfigClient.java, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/org/wso2/carbon/logging/remote/config/ui/i18n/Resources.properties, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/add_remote_server_config-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/js/loggingconfig.js, components/logging/org.wso2.carbon.logging.remote.config.ui/src/main/resources/web/log-config/process_add_remote_server_config-ajaxprocessor.jsp, components/logging/org.wso2.carbon.logging.service/pom.xml, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/LoggingConstants.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfigService.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/data/RemoteServerLoggerData.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigDataHolder.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigServiceComponent.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/util/Utils.java, components/logging/org.wso2.carbon.logging.updater/pom.xml, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/RemoteLoggingConfigUpdater.java, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/internal/DataHolder.java, components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/internal/LoggingUpdaterServiceComponent.java, service-stubs/logging/org.wso2.carbon.logging.remote.config.stub/src/main/resources/RemoteLogConfig.wsdl
This PR adds changes related to the features done for common criteria certification requirements.
=> Add features related to the common criteria certification

components/ntask/org.wso2.carbon.ntask.core/pom.xml, features/ntask/org.wso2.carbon.ntask.core.feature/pom.xml, pom.xml
> Update commons-codec to 1.16.0
=> Update commons-codec to 1.16.0

features/ntask/org.wso2.carbon.ntask.core.feature/pom.xml, pom.xml
=> Revert commons change

features/reporting/org.wso2.carbon.reporting.server.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.template.ui.feature/pom.xml, features/reporting/org.wso2.carbon.reporting.ui.feature/pom.xml
=> Remove beanutils wso2 orbits 

pom.xml
=> Update guava version

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
$subject
Related to https://github.com/wso2/product-is/issues/21374
=> Add new filter constants related to tenants filter API

pom.xml
$subject
Related issue: https://github.com/wso2/product-is/issues/21200
> Link to the PR for changes to the training content in …
=> Upgrade hector-core version

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingServerException.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/dao/RemoteLoggingConfigDAO.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/dao/impl/RegistryBasedRemoteLoggingConfigDAO.java
$subject. Improves https://github.com/wso2/carbon-commons/pull/499
=> Improve RemoteLoggingConfigDAO by introducing dedicated Exception

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/dao/RemoteLoggingConfigDAO.java, components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/dao/impl/RegistryBasedRemoteLoggingConfigDAO.java
$subject. Improves https://github.com/wso2/carbon-commons/pull/499
=> Improve RemoteLoggingConfigDAO method names

components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java
$subject. Improves https://github.com/wso2/carbon-commons/pull/499
=> Improve Optional data handling in RemoteLoggingConfig

pom.xml
=> Fix hard corded dependencies to use project version.

pom.xml
=> Fix hard corded dependencies to use project version properly.

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/listeners/TenantMgtListener.java
=> Re add missing tenant mgt listener methods

components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/beans/TenantInfoBean.java
$subject
**Merge in order:**
- https://github.com/wso2/identity-organization-management-core/pull/172
- https://github.com/wso2/carbon-commons/pull/513
- https://github.com/wso2/carbon-kernel/pull/4276
- https://github.com/wso2-extensions/identity-organization-management/pull/500
- https://github.com/wso2/carbon-multitenancy/pull/290
- https://github.com/wso2/carbon-identity-framework/pull/6685
- https://github.com/wso2/identity-api-server/pull/862
- https://github.com/wso2/identity-api-user/pull/263
=> Introduce Tenant Name to Tenant Management API

components/application-mgt/org.wso2.carbon.application.upload/src/main/java/org/wso2/carbon/application/upload/CarbonAppUploader.java
The CarbonAppUploader allows authenticated users with admin privilege to upload arbitrary files to any where in the server. An attacker can leverage this to write shell files with extension “.jsp” and perform remote code execution.
This vulnerability is eliminated by validating the file name against the expected file extension which is jar files. Also the file name is sanitised to avoid path traversal.
Additionally, it is ensured that the temporarily created file is deleted if an exception is thrown.
Public fix for the internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8556
=> Restrict malicious file upload

components/logging/org.wso2.carbon.logging.view/src/main/resources/META-INF/services.xml, components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/resources/META-INF/services.xml
=> Improve services.xml configs
