wso2/carbon-commons

- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
- authorizePermissionsToLoggedInUser() called by addTopic() and it's used by TopicManagerAdminService and CarbonEventBroker. authorizePermissionsToLoggedInUser() call moved to updatePermission() and it's only called by TopicManagerAdminService. By this way it's restricted to create internal role by topic name only for web service.
> Internal role creation for all topic is restricted

- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
When giving permission to logged in user in RegistryTopicManager#addTopic() we need to give publish and subscribe permissions too.
> fixing g-reg event subscription issue by modifying PR #99

- features/event/org.wso2.carbon.event.ui.feature/pom.xml
- org.wso2.carbon.um.ws.api.stub bundle removed from org.wso2.carbon.event.ui.feature
> Removing org.wso2.carbon.um.ws.api.stub in event feature

- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
Fix for JIRA - https://wso2.org/jira/browse/MB-1081
Added if condition to check the return type of userRegistry.get() before casting class. This will avoid trying to get child resources where children are not exist.
> [MB-1081] Event Component - ClassCast exception fixed in adding topic subscription

- components/event/org.wso2.carbon.event.client/src/main/java/org/wso2/carbon/event/client/broker/BrokerClient.java
- components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/try_it_out_invoke_ajaxprocessor.jsp
JIRA - https://wso2.org/jira/browse/MB-1200
See JIRA for error occurred.
This PR will add another method to BrokerClient.java which will allow to publish messages to topic. The method will take in an XML string as message content. Within the method this string will be converted to an OMElement and then published to the topic.
> [MB-1200] Added new method to publish messages to topics in event component.

- components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subscription_ajaxprocessor.jsp
Empty string propagates to back-end and exception thrown back to ui due to UI validation didn't handle empty strings.
In 'treecontrol.js' 'performSubscribe()' line424 error catches by searching response string for "Error:".
With this fix ui validation will catch empty strings from event sink url and throws response with "Error:" String.
jira - https://wso2.org/jira/browse/MB-1281
> [MB-1281] Fix error validation in event sink url

- components/event/org.wso2.carbon.event.admin/src/main/java/org/wso2/carbon/event/admin/internal/TopicManagerAdminService.java
- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
This fix has removed @Deprecated from service as it results in a runtime error. Then this fix also introduced fix (https://wso2.org/jira/browse/ESBJAVA-2506) that was given to 4.4.x version but not present in 4.5.x release. Without this fix https://github.com/wso2/product-esb/blob/master/modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/mediators/rule/ESBJAVA2506RuleFetchFromRegistryFailsForTheFirstTime.java intergration test is getting failed.
> Esb anlaytic upgrade

- components/event/org.wso2.carbon.event.admin/src/main/java/org/wso2/carbon/event/admin/internal/TopicManagerAdminService.java
- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/topic/registry/RegistryTopicManager.java
This fix has removed @Deprecated from service as it results in a runtime error. Then this fix also introduced fix (https://wso2.org/jira/browse/ESBJAVA-2506) that was given to 4.4.x version but not present in 4.5.x release.
> ESB Carbon Analytics Common Upgrade

- pom.xml
This fix is required to to build the product g-reg when updated to kernel 4.4.6 version
> CCOMMONS-13 - Jasper report version update

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
Fix setting the correct state when a task is resumed in a clustered environment.
Resolves https://github.com/wso2/carbon-commons/issues/274
Unit / integration test is not possible to verify this fix, hence the issue can be only observed in a clustered environment
> Fix issue when task resume.

- components/deployment-synchronizer/org.wso2.carbon.deployment.synchronizer/src/main/java/org/wso2/carbon/deployment/synchronizer/repository/CarbonRepositoryUtils.java
This removes the registry lookup logic when the depsync config is null or empty in the carbon.xml.
> CARBON-15453: Remove registry lookup for depsync config

- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/data/LogEvent.java
- components/logging/org.wso2.carbon.logging.view.ui/src/main/resources/org/wso2/carbon/logging/view/ui/i18n/Resources.properties
- components/logging/org.wso2.carbon.logging.view.ui/src/main/resources/web/log-view/application_log_viewer.jsp
- components/logging/org.wso2.carbon.logging.view.ui/src/main/resources/web/log-view/index.jsp
- service-stubs/logging/org.wso2.carbon.logging.view.stub/src/main/resources/LogViewer.wsdl
Fixed viewing large messages through the System logs of the Management Console without breaking the UI
Resolves https://wso2.org/jira/browse/CARBON-16109
> Fix view large messages through the System logs

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskManager.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/AbstractQuartzTaskManager.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/LocalTaskActionListener.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/remote/RemoteTaskManager.java
Resolves: https://github.com/wso2/product-ei/issues/1135
Enables writting a listener to be notified when a an action is performed on a task.
Adds a listener to 'AbstractQuartzTaskManager' to be notified when an action is performed on a task. Also notifies listeners when a local task is deleted.
This fix enables writting a listener to be notified when a an action is performed on a task by the 'AbstractQuartzTaskManager'.
N/A. This is an internal implementation which is not useful to an end user.
N/A. The implementation is done as a resolution to an issue which is an edge case in CAR deployment with a JMS inbound endpoint.
N/A. The issue only occurs in a clustered environment.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- …
> Add Local task deletion listener to be notified

- components/application-mgt/org.wso2.carbon.application.mgt.ui/src/main/resources/META-INF/component.xml
- components/application-mgt/org.wso2.carbon.application.mgt/src/main/resources/META-INF/services.xml
- components/application-mgt/org.wso2.carbon.application.upload/src/main/resources/META-INF/services.xml
Currently, the list/add actions for connectors and carbon apps are assigned to "permission/admin/manage" root level permission. In a scenario where a user needs to give only specific permissions (e.g. identity/user/add) under "permission/admin/manage", the current approach will not work. Therefore adding more granular permissions.
Git Issue       : https://github.com/wso2/product-ei/issues/932
> Add granular permissions for capps and connectors

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskInfo.java
- service-stubs/remote-tasks/org.wso2.carbon.remote-tasks.stub/src/main/resources/RemoteTaskAdmin.wsdl
> Resolves https://wso2.org/jira/browse/ESBJAVA-5234
> This is to fix the following exception thrown when a scheduled task is created with large task interval values(> Integer.MAX_VALUE). java.lang.IllegalArgumentException: Repeat interval must be >= 0. 
> The above exception is thrown due to casting a long into int, since the task interval is defined as int. So to fix this, the task interval data type is changed to long.
> N/A
> Fix for the exception thrown when a scheduled task is created with large task interval values(> Integer.MAX_VALUE)
> N/A
> N/A
> N/A. This fix includes a change for an internal representation of a parameter.
> N/A
- Integration tests
> org.wso2.carbon.esb.scheduledtask.test.TaskWithLargeIntervalValueTestCase (https://github.com/wso2/product-ei/pull/1112)
- …
> [Scheduled Task] Change data-type of task interval to long

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RuleBasedLocationResolver.java
Prevent task getting scheduled in not assign nodes.
Resolves https://wso2.org/jira/browse/ESBJAVA-5286
Get a pinned server kind behavior and prevent task getting scheduled if allowed node available in the cluster.
> Link to the PR …
> Throw an exception if the rule does not match

- components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/subscription/registry/RegistrySubscriptionManager.java
Fix the issue of server not starting when the registry resource is not available. As the fix we have avoided throwing the EventBrokerException when the subscription registry resource is not available. This will enable initializing CarbonEventBroker for available subscriptions.
Fixed https://github.com/wso2/product-ei/issues/1830
> Fix product-ei#1830

- components/application-mgt/org.wso2.carbon.application.mgt.ui/src/main/resources/web/carbonapps/index.jsp
> Filter users who don't have permissions to delete capps.
> Delete option should not be visible to users who don't have necessary permissions.
> Check for user permissions in the jsp file
> https://github.com/wso2/carbon-commons/pull/306
> JDK8
> Fix wso2/product-ei/issues/2164

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
>Resolves [#2172](https://github.com/wso2/product-ei/issues/2172) 
> The scheduled task runs on both worker nodes when performing rapid continuous rolling restarts of worker nodes due to not having distributed synchronization on registerTask method.
> Add distributed lock to the method which is used to register task.
> Add distributed synchronization for register task in clustered environment

- components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subscription.jsp
- components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/add_subtopic.jsp
> Add encoding to variables used in JSP pages.
> Protect against XSS
> Add necessary encodings
> Fix XSS vulnerability

- components/application-mgt/org.wso2.carbon.application.mgt/src/main/java/org/wso2/carbon/application/mgt/ApplicationAdmin.java
- components/ndatasource/org.wso2.carbon.ndatasource.capp.deployer/pom.xml
- components/ndatasource/org.wso2.carbon.ndatasource.capp.deployer/src/main/java/org/wso2/carbon/ndatasource/capp/deployer/DataSourceCappDeployer.java
- features/ndatasource/org.wso2.carbon.ndatasource.feature/pom.xml
- pom.xml
> Export org.wso2.carbon.ndatasource.capp.deployer package to use in the org.wso2.carbon.dataservices.capp.deployer.
Remove code segments related to DafaultAppDeploye data services in ApplicationAdmin.java.
Getting an error while deploying a data source which has a secret alias as the password via a capp, changed secret alias evaluation to true.
Include org.wso2.carbon.ndatasource.capp.deployer.server.feature to org.wso2.carbon.ndatasource.ui.feature
- https://github.com/wso2/carbon-kernel/pull/1900
- https://github.com/wso2/carbon-data/pull/225
- JDK version: 1.8.0_181
- Operating system: Mac OS High Sierra
> Fix wso2/product-ei#2939 and wso2/product-ei#2938

- components/tryit/org.wso2.carbon.tryit/src/main/java/org/wso2/carbon/tryit/TryitRequestProcessor.java
This stops the ability to continue using the tryit functionality through a direct link even after signing out from admin console.
> Block the tryit functionality unless authenticated

- components/tryit/org.wso2.carbon.tryit/src/main/java/org/wso2/carbon/tryit/TryitRequestProcessor.java
This blocks the tryit functionality if the property tryItFunctionalityDisabled=true is added to the EI_HOME/conf/carbon.properties file.
> Block the tryit functionality depending on the config

- service-stubs/org.wso2.carbon.identity.entitlement.stub/src/main/resources/EntitlementPolicyAdminService.wsdl
Same package is duplicated in 
carbon-commons https://github.com/wso2/carbon-commons/tree/master/service-stubs/org.wso2.carbon.identity.entitlement.stub
and
carbon-identity-framework https://github.com/wso2/carbon-identity-framework/tree/master/service-stubs/identity/org.wso2.carbon.identity.entitlement.stub
Since carbon deployment uses the one from carbon commons and carbon mediation uses the one from carbon-identity-framework we are getting duplicate jars.
Since there are few changes in identity framework, we are incorporating it to carbon-commons and the carbon-mediation will also use the dependency from carbon commons.
> Move recent changes of EntitlementPolicyAdminService.wsdl from identity framework to commons

- components/event/org.wso2.carbon.event.ui/src/main/resources/web/topics/topic_add.jsp
HTML-encode parameters used in HTML elements
> carbon-event-ui: update topic_add.jsp

- components/logging/org.wso2.carbon.logging.admin.ui/src/main/resources/web/log-admin/js/loggingadmin.js
Update "Persist all configuration changes" UI logic to read the correct checkbox state and maintain the checkbox state after a global log4j property update
Fixes #wso2/product-ei/issues/3760
> Fix global log4j settings persist issue in admin ui

- components/system-statistics/org.wso2.carbon.statistics/src/main/java/org/wso2/carbon/statistics/internal/StatisticsServiceComponent.java
> Fix Nullpointer exception when shutting down IS server.
```
[SCR] Exception occurred while unbinding reference Reference[name = config.context.service, interface = org.wso2.carbon.utils.ConfigurationContextService, policy = dynamic, cardinality = 1..1, target = null, bind = setConfigurationContextService, unbind = unsetConfigurationContextService]
Details:
Problematic reference = Reference[name = config.context.service, interface = org.wso2.carbon.utils.ConfigurationContextService, policy = dynamic, cardinality = 1..1, target = null, bind = setConfigurationContextService, unbind = unsetConfigurationContextService]
of service component = statistics.service.component
component implementation class = org.wso2.carbon.statistics.internal.StatisticsServiceComponent
located in bundle with …
```
> Fix Nullpointer exception when shutting down IS server.

- components/tryit/org.wso2.carbon.tryit/src/main/java/org/wso2/carbon/tryit/TryitRequestProcessor.java
Port the fix wso2/carbon-commons#340 & wso2/carbon-commons#341
> Block the tryit functionality depending on the config or authentication

- components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/LoggingUpdaterConstants.java
Updating const name as per https://github.com/ops4j/org.ops4j.pax.logging/blob/master/pax-logging-api/src/main/java/org/ops4j/pax/logging/spi/support/EventAdminConfigurationNotifier.java#L61
```java
@Override
public void configurationError(Throwable t) {
EventAdmin ea = tracker.getService();
if (ea != null) {
LOG.warn("Sending Event Admin notification (configuration error) to " + PaxLoggingConstants.EVENT_ADMIN_CONFIGURATION_TOPIC);
Map<String, Object> properties = new HashMap<>();
properties.put("exception", t);
ea.postEvent(new Event(PaxLoggingConstants.EVENT_ADMIN_CONFIGURATION_TOPIC, new EventProperties(properties)));
} else {
LOG.warn("Logging configuration problem. (Event Admin service unavailable - no notification sent).", t);
}
}
```
> Fix exception const

- components/logging/org.wso2.carbon.logging.view/src/main/java/org/wso2/carbon/logging/view/appenders/LoggingAppender.java
Fixes: https://github.com/wso2/product-apim/issues/9284
Retrieve the IP only once during an API invoke call from APIM 3.1.0 which will stop dropping the performance.
- Introduced a static block inside **LoggingAppender** class which basically does the function that getIP function was doing.
- Performance was increased by 25% for the issue https://github.com/wso2/product-apim/issues/9284
> Retrieve the IP inside a static block

- components/ndatasource/org.wso2.carbon.ndatasource.ui/src/main/resources/web/ndatasource/validateconnection-ajaxprocessor.jsp
This is to encode error message when the test connection is not successful
> Encode error message in datasource configuration ui

- components/logging/org.wso2.carbon.logging.updater/pom.xml
Reverts wso2/carbon-commons#448
Reason - To fix the test failures and will address the changes afters stabilising the integrations tests of the IS
> Revert "Rollback to log4j1"

- components/logging/org.wso2.carbon.logging.view/pom.xml
- pom.xml
- Temporarily increase the version range of the pax logging until the pax logging is upgraded in IS
- The pax logging upgrade for "org.wso2.org.ops4j.pax.logging" (WSO2 managed) is rollbacked to use the previous 3rd party pax-logging dependency.
> Revert pax logging upgrade and temporarily increase version pax logging version range

- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/TaskServiceContext.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RoundRobinTaskLocationResolver.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/RuleBasedLocationResolver.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusterGroupCommunicator.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/impl/clustered/ClusteredTaskManager.java
- components/ntask/org.wso2.carbon.ntask.core/src/main/java/org/wso2/carbon/ntask/core/internal/TasksDSComponent.java
As we have deprecated the Hazelcast based distributed caching use cases in APIM, removing the Hazelcast dependency from carbon-commons repository.
Primary goal is to totally remove Hazelcast dependency from API Manager. In order to achieve that, we are removing Hazelcast from repositories such as,
1. Andes
2. Carbon Business Messaging
3. Carbon Event Processing
4. WSO2 Synapse
5. Carbon Mediation
6. Carbon Commons
7. Carbon Kernel
8. Siddhi
As API Manager is not using Hazelcast, and also was informed as during the effort of upgrading Hazelcast from 3.12.x to 4.2.x, the carbon-commons repository was not tracked as IS product dependent component, we are removing Hazelcast use-cases from Carbon Commons.
NTask Core is using Hazelcast and since it is not possible to remove the whole component …
> [4.9.x] Hazelcast Removal

- components/logging/org.wso2.carbon.logging.service/pom.xml
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfigService.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigServiceComponent.java
To support https://github.com/wso2/product-is/issues/16588, we need to register remote logging as a OSGi service.
> Add remote logging configuration service

- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigDataHolder.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigServiceComponent.java
- Remove remote logging clustering message passing related logic
- https://github.com/wso2/carbon-commons/pull/478
- https://github.com/wso2/product-is/issues/16697
- https://github.com/wso2/api-manager/issues/1565
> Remove clustering message passing logic as it will be sent via a different PR

- components/logging/org.wso2.carbon.logging.updater/pom.xml
- pom.xml
This PR updates the org.osgi.service.cm version range to [1.3.100, 2.0.0) in the org.wso2.carbon.logging.updater component.
> [4.9.x] Update version range for org.osgi.service.cm

- components/logging/org.wso2.carbon.logging.updater/src/main/java/org/wso2/carbon/logging/updater/LogConfigUpdater.java
This will fix https://github.com/wso2/api-manager/issues/2589
The issue has been introduced due to the pax logging upgrade in the product hence the log has to be added to the run() method where the changes will be monitored and applied
> Add info log after log4j config updates

- components/tenant-mgt-common/org.wso2.carbon.tenant.common/src/main/java/org/wso2/carbon/stratos/common/constants/TenantConstants.java
Introduce new error codes for tenant management API to handle following errors.
- TM-60020: Owner id is not matching for the given tenant id 
- TM-60021: Tenant is partially created / updated when provided claims fails validation. Related to https://github.com/wso2/product-is/issues/21346
- https://github.com/wso2/product-is/issues/21271
> Add error codes for tenant API

- components/logging/org.wso2.carbon.logging.appender.http/pom.xml
- components/logging/org.wso2.carbon.logging.appender.http/src/main/java/org/wso2/carbon/logging/appender/http/SecuredHttpAppender.java
- components/logging/org.wso2.carbon.logging.appender.http/src/main/java/org/wso2/carbon/logging/appender/http/utils/AppenderConstants.java
- components/logging/org.wso2.carbon.logging.service/pom.xml
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/LoggingConstants.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfig.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/RemoteLoggingConfigService.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/dao/impl/RegistryBasedRemoteLoggingConfigDAO.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigDataHolder.java
- components/logging/org.wso2.carbon.logging.service/src/main/java/org/wso2/carbon/logging/service/internal/RemoteLoggingConfigServiceComponent.java
- pom.xml
- Added new methods to get remote server credentials without the secrets
- Encrypt the secrets added to the log4j.properties file
```toml
[remote_logging]
hide_secrets=true
```
> Hiding remote log credentials from the UI and API
